### ISSUE TITLE
Remove Token from dashboard.html on public repository

### ISSUE THREAD

**Issue by michael-krieger** [54x1/54x1.github.io#16]
In case you are not aware of it... @54x1 you are leaking a Dynatrace API token in your file https://github.com/54x1/54x1.github.io/blob/master/dashboard.html on a public repository, readable to everyone. Please, for security reasons, 1) remove this token from your public repository and 2) deactivate/rotate this token on your Dynatrace tenant. Thx!

**Comment by 54x1** [comment]
removed all relating issues off github

**Comment by michael-krieger** [comment]
@54x1 please be aware that the token is still publicly visible via git commit history. Please take a look at https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository for details on how to remove secrets from your git history.
